-- Add new card types for Eldritch Horror 4x4 classification
ALTER TYPE card_type ADD VALUE IF NOT EXISTS 'WEAPON';
ALTER TYPE card_type ADD VALUE IF NOT EXISTS 'ALLY';
ALTER TYPE card_type ADD VALUE IF NOT EXISTS 'SERVICE';
ALTER TYPE card_type ADD VALUE IF NOT EXISTS 'LOCATION_ENCOUNTER';
ALTER TYPE card_type ADD VALUE IF NOT EXISTS 'RESEARCH_ENCOUNTER';
ALTER TYPE card_type ADD VALUE IF NOT EXISTS 'OTHER_WORLD_ENCOUNTER';
ALTER TYPE card_type ADD VALUE IF NOT EXISTS 'EXPEDITION_ENCOUNTER';
ALTER TYPE card_type ADD VALUE IF NOT EXISTS 'ARTIFACT';
ALTER TYPE card_type ADD VALUE IF NOT EXISTS 'MYTHOS';
ALTER TYPE card_type ADD VALUE IF NOT EXISTS 'MYSTERY';
